### ISSUE TITLE
GrapherJS executes user input without any filtering.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [Michael2-3B/GrapherJS#1]
# Using eval() on user input is a REALLY BAD IDEA.

Using `eval()` on user input is extremely dangerous and basically goes against the #1 rule of website security.

I suggest using either some form of input validation or having the user press buttons (like a calculator) to add to the formula. I recommend the second option because simply determining what is safe to execute is extremely difficult.

Here's some code that you can pass your function string into that both cleanses it and does simple conversions, like "^" to "**" and "abs(" to "Math.abs(". Note that this is a **temporary solution** that is designed to essentially buy you time until you can figure out how to solve the problem by yourself.

```
function fixFunction(functionString) {
  functionString = functionString.replace(/[^a-z+\-*^=0-9\(\)/]/g,"");
  changes = [
    ["^","**"],
    ["sin(","Math.sin("],
    ["cos(","Math.cos("],
    ["tan(","Math.tan("],
    ["abs(","Math.abs("],
    ["sqrt(","Math.sqrt("]
  ];
  changes.forEach(function(change) {
    functionString = functionString.replace(change[0],change[1]);
  });
  return functionString
}
```

Read [this](https://stackoverflow.com/a/1651146) to fully understand why this is a bad idea.

Although this isn't necessarily a huge problem on your site, this is an important thing to understand in the future.

**Comment by Michael2-3B** [comment]
The fixFunction function has been added, which as you said, will work as a temporary solution. I hope to look further into the problem soon.

**Comment by Legend-of-iPhoenix** [comment]
Just alerting you, I'm working on a fix for this bug, give me a few minutes. (and dammit, you changed the code lol)

**Comment by Michael2-3B** [comment]
Oh, awesome! And yeah, I did just change the code (most recently: at 5:18 PM CST). I'm finished now for the moment. Just added an actual text entry box that can always be seen.

**Comment by Legend-of-iPhoenix** [comment]
Yeah, I made a PR with my changes.
